Repository Icinga/ipl-web, pull requests merged in 2023-01, with the labels that each got.

#107 Update Checkout Action to v3
  .github/workflows/php.yml
Labels: cla/signed

#106 IcingaFormDecorator: Add support for `FieldsetElement`
  src/FormDecorator/IcingaFormDecorator.php
Labels: enhancement, cla/signed

#109 PHP 8.2 Support
  .github/workflows/php.yml
Labels: cla/signed

#111 SearchBar: Don't change `q`'s value during validation
  src/Control/SearchBar.php
Labels: bug, cla/signed
