Repository Icinga/ipl-web, pull requests merged in 2023-06, with the labels that each got.

#155 Add `grid` icinga icon
  asset/css/icinga-icons.less
Labels: enhancement, cla/signed

#154 Add optional `$defaultSort` parameter for `SortControl::apply` method
  src/Compat/CompatController.php
  src/Control/SortControl.php
Labels: enhancement, cla/signed

#103 Differentation between equal like unequal and unlike
  asset/js/widget/FilterInput.js
  src/Common/StateBadges.php
  src/Control/SearchBar/Suggestions.php
  src/Filter/Parser.php
  src/Filter/QueryString.php
  src/Filter/Renderer.php
  tests/FilterTest.php
Labels: enhancement, cla/signed

#156 balls.less: Don't set the content color in `.ball-outline()`
  asset/css/balls.less
Labels: enhancement, cla/signed

#151 Add copy to clipboard button widget
  asset/css/copy-to-clipboard.less
  asset/js/widget/CopyToClipboard.js
  src/Widget/CopyToClipboard.php
Labels: enhancement, cla/signed

#158 Add `state-none` state-badge
  asset/css/state-badge.less
  asset/css/variables.less
Labels: enhancement, cla/signed

#160 Card: Make footer optional
  src/Common/Card.php
Labels: cla/signed

#161 TimeUntil: Add `data-ago-label` to allow automatic transitioning
  src/Widget/TimeUntil.php
Labels: enhancement, cla/signed

#127 CompatForm: Register form element namespace
  src/Compat/CompatForm.php
Labels: enhancement, cla/signed

#162 balls.less: Remove margin right of icons inside balls..
  asset/css/balls.less
Labels: bug, cla/signed

#164 SearchEditor: Support new operators `~` and `!~`
  src/Control/SearchEditor.php
Labels: bug, cla/signed
