Repository Icinga/ipl-web, pull requests merged in 2023-08, with the labels that each got.

#176 Properly validate user input in term inputs and filter inputs
  src/Control/SearchBar/ValidatedTerm.php
  src/FormElement/TermInput/RegisteredTerm.php
Labels: bug, cla/signed

#173 Process `POST` requests in `SortControl`
  src/Compat/CompatController.php
  src/Control/SortControl.php
Labels: enhancement, cla/signed

#181 Multi completion support
  asset/css/search-base.less
  asset/js/widget/BaseInput.js
  asset/js/widget/Completer.js
  asset/js/widget/FilterInput.js
  src/FormElement/TermInput.php
Labels: enhancement, cla/signed

#184 Enhance base input validation
  asset/js/widget/BaseInput.js
Labels: bug, cla/signed

#178 Introduce `ipl\Web\FormElement\TermInput\TermSuggestions`
  src/FormElement/TermInput/TermSuggestions.php
Labels: enhancement, cla/signed

#179 TermInput: Allow to arrange terms vertically
  asset/css/compat.less
  asset/css/search-base.less
  asset/js/widget/BaseInput.js
  asset/js/widget/FilterInput.js
  src/FormElement/TermInput.php
Labels: enhancement, cla/signed

#185 TermInput.js: Also accept new terms upon pushing Enter
  asset/js/widget/TermInput.js
Labels: bug, cla/signed

#187 SortControl: Re-populate the control in case a partial match is found
  src/Control/SortControl.php
Labels: bug, cla/signed

#188 css: Content following controls should not overlay them
  asset/css/controls.less
Labels: bug, cla/signed

#189 CSS: Adjust icinga icons path
  asset/css/icinga-icons.less
Labels: bug, cla/signed

#190 composer.json: Install ipl dependencies from main branch in tests
  composer.json
Labels: cla/signed

#159 Github Actions: Add Phpstan
  .github/workflows/php.yml
  composer.json
  phpstan-baseline.neon
  phpstan.neon
Labels: cla/signed

#191 Completer.js: Focus the selected item when selection starts
  asset/js/widget/Completer.js
Labels: bug, cla/signed

#167 Introduce `Style` element
  composer.json
  src/LessRuleset.php
  src/Style.php
  tests/LessRulesetTest.php
  tests/Lib/LessRulesetWithTestableRenderCss.php
  tests/Lib/StyleWithTestableRenderCss.php
  tests/Lib/TestableRenderCss.php
  tests/StyleTest.php
Labels: enhancement, cla/signed

#180 Undeprecate `StateBadge` class
  src/Widget/StateBadge.php
Labels: cla/signed
