Repository Icinga/ipl-web, pull requests merged in 2023-04, with the labels that each got.

#133 Do not autosubmit start with `NO_REPEAT` freq
  src/FormElement/ScheduleElement.php
Labels: bug, cla/signed

#48 CompatController: Introduce method `sendExtraUpdates()`
  src/Compat/CompatController.php
Labels: cla/signed

#137 Make icon style adjustable
  src/Widget/IcingaIcon.php
  src/Widget/Icon.php
Labels: enhancement, cla/signed

#138 ScheduleElement: Do not fail if `start` is populated with null
  src/FormElement/ScheduleElement.php
Labels: bug, cla/signed

#131 font: Add `icinga` glyph to Icinga Icons
  asset/css/icinga-icons.less
  asset/static/font/Icinga-Icons.eot
  asset/static/font/Icinga-Icons.svg
  asset/static/font/Icinga-Icons.ttf
  asset/static/font/Icinga-Icons.woff
Labels: cla/signed

#134 Enhance term input
  asset/js/widget/BaseInput.js
  asset/js/widget/Completer.js
  asset/js/widget/FilterInput.js
  asset/js/widget/TermInput.js
Labels: enhancement, cla/signed

#139 Add term input
  asset/css/compat.less
  asset/css/search-bar.less
  asset/css/search-base.less
  src/Control/SearchBar/ValidatedOperator.php
  src/Control/SearchBar/ValidatedTerm.php
  src/FormElement/TermInput.php
  src/FormElement/TermInput/RegisteredTerm.php
  src/FormElement/TermInput/Term.php
  src/FormElement/TermInput/TermContainer.php
  src/FormElement/TermInput/ValidatedTerm.php
Labels: enhancement, cla/signed

#128 AnnuallyFields: Drop usage of `onRegistered()` handler
  src/FormElement/ScheduleElement/AnnuallyFields.php
Labels: bug, cla/signed
