Repository Icinga/ipl-web, pull requests merged in 2023-09, with the labels that each got.

#195 Introduce `Url::setFilter()`
  src/Common/StateBadges.php
  src/Compat/SearchControls.php
  src/Url.php
  src/Widget/ContinueWith.php
  tests/UrlTest.php
Labels: enhancement, cla/signed

#196 phpstan: Update baseline file
  phpstan-baseline.neon
Labels: cla/signed

#192 TermSuggestions: Use `ipl\Stdlib\yield_groups`
  phpstan-baseline.neon
  src/FormElement/TermInput/TermSuggestions.php
Labels: cla/signed

#201 css: Transfer icingadb related searchbar styles to default control layout
  asset/css/compat.less
  asset/css/controls.less
Labels: bug, cla/signed

#197 Add different redirect options
  src/Compat/CompatController.php
Labels: enhancement, cla/signed

#198 Link: Allow to optionally enable modal view
  src/Widget/Link.php
Labels: enhancement, cla/signed

#200 SortControl: Apply the url's parameter if the form is not sent
  src/Control/SortControl.php
Labels: bug, cla/signed

#202 Introduce class `ipl\Web\Compat\StyleWithNonce`
  src/Compat/StyleWithNonce.php
  src/Style.php
Labels: cla/signed

#183 Integrate list and table widgets from Icinga DB Web
  asset/css/list/item-list.less
  asset/css/list/item-table.less
  asset/css/list/list-item.less
  asset/css/mixin/mixins.less
  asset/css/variables.less
  phpstan-baseline.neon
  src/Common/BaseItemList.php
  src/Common/BaseItemTable.php
  src/Common/BaseListItem.php
  src/Common/BaseOrderedItemList.php
  src/Common/BaseOrderedListItem.php
  src/Common/BaseTableRowItem.php
  src/Common/BaseTarget.php
  src/Widget/EmptyState.php
Labels: enhancement, cla/signed

#203 Url: Allow to unset the filter
  src/Url.php
  tests/UrlTest.php
Labels: cla/signed

#204 Add `EmptyStateBar` widget
  asset/css/empty-state.less
  asset/css/list/item-list.less
  asset/css/list/item-table.less
  asset/css/variables.less
  src/Common/BaseItemList.php
  src/Common/BaseItemTable.php
  src/Common/BaseOrderedItemList.php
  src/Widget/EmptyStateBar.php
Labels: enhancement, cla/signed

#205 EmptyStateBar: Don't use css class `empty-state`
  src/Widget/EmptyStateBar.php
Labels: cla/signed

#207 CompatController: Properly define `X-Icinga-Location-Query`
  src/Compat/CompatController.php
Labels: bug, cla/signed

#208 Revert "Add missing css variable and state-ball for state `unreachable`"
  asset/css/balls.less
  asset/css/variables.less
Labels: cla/signed
