Repository Icinga/ipl-web, pull requests merged in 2025-03, with the labels that each got.

#250 js: Provide polyfills for iterator.map, .find and .filter
  asset/js/iterator.js
Labels: cla/signed

#251 SearchBar: Fix scrollbar position in default-layout controls
  asset/css/controls.less
  asset/css/search-base.less
Labels: bug, cla/signed

#255 CompatController: Patch tab extensions correctly again
  src/Compat/CompatController.php
Labels: bug, cla/signed

#249 Display delete action when hovering over read-only term-input entries
  asset/css/search-base.less
  asset/css/variables.less
  asset/js/widget/TermInput.js
  src/FormElement/TermInput/TermContainer.php
Labels: cla/signed

#257 TermInput: Keep original minimum width of terms
  asset/css/search-base.less
  asset/js/widget/TermInput.js
  src/FormElement/TermInput/TermContainer.php
Labels: bug, cla/signed

#252 Introduce new item list/header layout implementation
  asset/css/item-layout.less
  asset/css/list/item-list.less
  asset/css/list/list-item.less
  asset/css/variables.less
  src/Common/BaseItemList.php
  src/Common/BaseListItem.php
  src/Common/BaseOrderedItemList.php
  src/Common/BaseOrderedListItem.php
  src/Common/ItemRenderer.php
  src/Layout/DetailedItemLayout.php
  src/Layout/HeaderItemLayout.php
  src/Layout/ItemLayout.php
  src/Layout/MinimalItemLayout.php
  src/Widget/ItemList.php
  src/Widget/ListItem.php
Labels: enhancement, cla/signed

#253 Introduce new item table layout implementation
  asset/css/list/item-table.less
  src/Common/BaseItemTable.php
  src/Common/BaseTableRowItem.php
  src/Layout/DetailedItemTableLayout.php
  src/Layout/ItemTableLayout.php
  src/Layout/MinimalItemTableLayout.php
  src/Widget/ItemTable.php
  src/Widget/ItemTable/ItemTableRenderer.php
  src/Widget/ItemTableRow.php
Labels: cla/signed

#258 Add class `ipl\Web\Widget\Ball`
  asset/css/balls.less
  src/Widget/Ball.php
  src/Widget/StateBall.php
Labels: enhancement, cla/signed
